version: '3.8'

services:
  transcript-tube:
    build: .
    image: transcript-tube:latest
    container_name: transcript-tube
    ports:
      - "8501:8501"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    # Descomente as linhas abaixo se quiser limitar recursos
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
