version: '3.8'

services:
  transcript-tube:
    build: .
    image: transcript-tube:latest
    container_name: transcript-tube
    ports:
      - "8501:8501"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_UI_HIDE_DEPLOY=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_BASE=dark
      - STREAMLIT_TOOLBAR_MODE=minimal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s